# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Δεληκούρα Αικατερίνη
title: Δημόσιος Υπάλληλος 
email: renadelikoyra@yahoo.gr
website: https://rena-delikoura.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  rana-delikoura
# facebook_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant

# Additional icon links
additional_links:
- title: Print version
  icon: far fa-file-pdf
  url: https://github.com/rena-delikoura/rena-delikoura.github.io/blob/master/rena-delikoura-cv.pdf?raw=true

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Δημόσιος υπάλληλος με εκτενή εμπειρία στο χώρο της υγείας στον διοικητικό τομέα, ακαδημαϊκή εκπαίδευση στην επιστήμη της ψυχολογίας και έντονη πολιτική δράση και ενδιαφέρον για τα κοινά.

content:

  - title: Επαγγελματική Εμπειρία # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Γενικό Νοσοκομείο Ιωαννίνων  "Γ.ΧΑΤΖΗΚΩΣΤΑ"
        sub_title: Διοικητικός Υπάλληλος 
        caption: 2010 – 
        description: |
          * Γραφείο Κινήσης
          * Οικονομικό τμήμα
          * Τακτική γραμματέας της Β΄/θμιας Υγειονομικής επιτροπής Ηπείρου με απόφαση Γενικού Γραμματέα Αποκεντρωμένης Διοίκησης  Ηπείρου - Δυτικής Μακεδονίας
      
      - layout: left
        title: Κέντρο Παιδικής Μέριμνας Θηλέων Ρόδου
        sub_title: Διοικητικός Υπάλληλος 
        caption: 2008 - 2010
        description: | # this will include new lines to allow paragraphs
          Γενικά διοικητικά καθηκόντα 
          

      - layout: left
        title: Γενικό Νοσοκομείο Ιωαννίνων  "Γ.ΧΑΤΖΗΚΩΣΤΑ"
        sub_title: Διοικητικός Υπάλληλος 
        caption: 2002 - 2008
        description: | # this will include new lines to allow paragraphs
          * Γραφείο κίνησης

      - layout: left
        title:  Περιφερειακό Γενικό Νοσοκομείο - Μαιευτήριο "Έλενα Βενιζέλου"
        sub_title: 
        caption: 1997 - 2002
        description: | # this will include new lines to allow paragraphs
          

  - title: Πολιτική Δράση
    layout: list
    content: 
      - layout: left
        title: Παμβώτιδα Νέα Εποχή
        caption: 1998
        description: | 
          Yποψήφια με το συνδυασμό "Παμβώτιδα Νέα Εποχή" στο τοπικό του Δ.Δ. Πλατανιάς.
    
      - layout: left
        title: Παμβώτιδα Νέα Εποχή
        caption: 2002
        description: | 
          Yυποψήφια  με το συνδυασμό "Παμβώτιδα Νέα Εποχή" στο τοπικό Δ.Δ. Πλατανιάς και εκλεγμένη για 2 έτη.

      - layout: left
        title: Ενότητα πολιτών - Νέα Γιάννενα
        caption: 2010
        description: | 
          Υποψήφια με το συνδυασμό "Ενότητα πολιτών - Νέα Γιαννενα" στο τοπικό του Δ.Δ. Πλατανιάς.

      - layout: left
        title: Ένωσης Γυναικών Ελλάδος 
        caption: 2012
        description: | 
          Εκλεγμένη της Ένωσης Γυναικών Ελλάδος (ΕΓΕ) το 2012 Παράρτημα Ιωαννίνων και ενεργο μέλος.

      - layout: left
        title: Nομαρχιακή επιτροπή ΠΑΣΟΚ Ιωαννίνων
        caption: 2014
        description: | 
          Εκλεγμένη στην νομαρχιακή ΠΑΣΟΚ Ιωαννίνων.

      - layout: left
        title: Γιάνεννα Νέα Εποχή
        caption: 2019
        description: | 
          Υποψήφια με το συνδιασμο Γιάνεννα Νέα Εποχή για δημοτικός συύβουλος Δήμου Ιωαννιτών. 
      
      - layout: left
        title: ΟΚΠΑΠΑ Ιωαννίνων
        caption: 2019
        description: | 
          Aναπληρωματικό μέλος του ΟΚΠΑΠΑ ΟΚΠΑΠΑ Ιωαννίνων έως και σήμερα.
      
      - layout: left
        title: Νομαρχιακή επιτροπή ΠΑΣΟΚ Ιωαννίνων
        caption: 2022
        description: | 
          Εκλεγμένη στην νομαρχιακή ΠΑΣΟΚ Ιωαννίνων. 


  - title: Εκπαίδευση # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Παν/μιο Ιωαννίνων
        caption: 20018 - 2022
        sub_title: Ψυχολόγος
        description: | # this will include new lines to allow paragraphs
          Στόχος του Προγράμματος Προπτυχιακών Σπουδών του Τμήματος Ψυχολογίας είναι η παροχή ολοκληρωμένης και υψηλής ποιότητας εκπαίδευσης στους/στις φοιτη-τές/τριες στο αντικείμενο της Ψυχολογίας.
          
          Το Προπτυχιακό Πρόγραμμα Σπουδών (Π.Π.Σ.) του Τμήματος Ψυχολογίας του Πανεπιστημίου Ιωαννίνων (Π.Ι.) είναι διάρκειας τεσσάρων ακαδημαϊκών ετών. Το Π.Π.Σ. του Τμήματος βρίσκεται σε εναρμόνιση με το Ευρωπαϊκό Σύστημα Μεταφοράς και Συσσώρευσης Πιστωτικών Μονάδων (ECTS).

      - layout: left
        title:  Εξειδίκευση οικονομικές υπηρεσίες τομέα Οικονομίας και Διοίκησης
        caption: 2005 - 2006
        sub_title: Πτυχιο β΄κυκλου
        description: | # this will include new lines to allow paragraphs
          Εξειδικευμένες γνώσεις και δεξιότητες με εφαρμογές στις αρχές της επιστήμης του management, της οικονομίας και των δημοσίων σχέσεων με στόχο την στελέχωση των διοικητικών και οικονομικών υπηρεσιών, των μονάδων του ιδιωτικού ή δημοσίου τομέα.

      - layout: left
        title: Μέση Τεχνική Επαγγελματική Νοσηλευτική Σχολή Αθηνών
        caption: 1994 - 1995
        sub_title: Σχολή «Αμαλία Φλέμινγκ»
        description: | 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag